config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :doctors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { maximum: 35 }
  validates :zip, length: { maximum: 5, too_long: 'is too long (maximum is 5 digits)'}
  
  validates_inclusion_of :experience, :in => 1..100
  
end

app/models/pet.rb
class Pet < ApplicationRecord
   CATEGORY = ["Dog", "Cat", "Bird"]
   
   validates :name, presence: true
   validates :age, presence: true
   validates :weight, presence: true
   validates :last_visit, presence: true
   
   validates :breed, presence: true
   validates :breed, length: { maximum: 35 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end
  
  def create
    doctor = Doctor.new(doctor_params)
    if doctor.save
      redirect_to doctor_path(doctor), notice: 'Vet created'
    else
      flash.notice = "Error occurred"

      render :new
    end
  end
  
  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    doctor = Doctor.find(params[:id])
    doctor.update_attributes(doctor_params)

    redirect_to doctor_path(doctor), notice: 'Doctor updated'
  end
  
  private
  
  def doctor_params
    params.require(:doctor).permit(:name, :address, :city, :state, :zip, :school, :experience)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :age, :weight, :category, :last_visit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor)do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>

  <p>
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </p>

  <p>
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </p>
  
  <p>
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </p>
  
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/doctors/edit.html.erb
<%= render 'form' %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= link_to doctor.name, doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Vet</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p>
  <%= @doctor.name %>
</p>

<p>
  <%= @doctor.address %>
</p>

<p>
  <%= @doctor.city %>
</p>

<p>
  <%= @doctor.state %>
</p>

<p>
  <%= @doctor.zip %>
</p>

<p>
  School: <%= @doctor.school %>
</p>

<p>
  Experience:  <%= @doctor.experience %> years.
</p>


<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>

</html>

app/views/pets/_form.html.erb
<%= form_for(pet) do |f| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :breed %>
    <%= f.text_field :breed %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.select(:category, Pet::CATEGORY) %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div class="field">
    <%= f.label :last_visit %>
    <%= f.datetime_select :last_visit %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Type</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Last visit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.breed %></td>
        <td> <%= pet.category %> </td>
        <td><%= pet.age %></td>
        <td><%= pet.weight %></td>
        <td><%= pet.last_visit %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Category:</strong>
  <%= @pet.category %>
</p>


<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet.weight %>
</p>

<p>
  <strong>Last visit:</strong>
  <%= @pet.last_visit %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>